LOAD DATA LOCAL INFILE "user.dat" INTO TABLE Users FIELDS TERMINATED BY "<>";
LOAD DATA LOCAL INFILE "dininghall.dat" INTO TABLE DiningHall FIELDS TERMINATED BY "<>";
LOAD DATA LOCAL INFILE "student.dat" INTO TABLE Student FIELDS TERMINATED BY "<>";
LOAD DATA LOCAL INFILE "faculty.dat" INTO TABLE Faculty FIELDS TERMINATED BY "<>";
LOAD DATA LOCAL INFILE "administrator.dat" INTO TABLE Administrator FIELDS TERMINATED BY "<>";
LOAD DATA LOCAL INFILE "hours.dat" INTO TABLE Hours FIELDS TERMINATED BY "<>";
LOAD DATA LOCAL INFILE "ratings.dat" INTO TABLE Ratings FIELDS TERMINATED BY "<>
";
LOAD DATA LOCAL INFILE "food.dat" INTO TABLE Food FIELDS TERMINATED BY "<>";
LOAD DATA LOCAL INFILE "foodtype.dat" INTO TABLE FoodType FIELDS TERMINATED BY "<>";

